"use strict";
var term = require("terminal-kit").terminal;
var Point_1 = require("./Point");
var HorizontalLine_1 = require("./HorizontalLine");
var VerticalLine_1 = require("./VerticalLine");
var p01 = new Point_1["default"](2, 1, "*");
var p02 = new Point_1["default"](8, 10, "#");
var hl = new HorizontalLine_1["default"](2, 6, 3, "@");
var vl = new VerticalLine_1["default"](4, 7, 2, "+");
p01.Draw();
hl.Draw();
vl.Draw();
p02.Draw();
