"use strict";
var term = require("terminal-kit").terminal;
var Point_1 = require("./Point");
var HorizontalLine_1 = require("./HorizontalLine");
var VerticalLine_1 = require("./VerticalLine");
var p02 = new Point_1["default"](3, 3, "#");
var pReset = new Point_1["default"](0, 11, "");
var hlTop = new HorizontalLine_1["default"](1, 20, 1, "@");
var hlBot = new HorizontalLine_1["default"](1, 20, 10, "@");
var vlLeft = new VerticalLine_1["default"](1, 10, 1, "@");
var vlRight = new VerticalLine_1["default"](1, 10, 20, "@");
term.clear();
hlTop.Draw();
hlBot.Draw();
vlLeft.Draw();
vlRight.Draw();
p02.Draw();
pReset.Draw();
